Add logic for persisting fernet key to airflow.cfg
aws/aws-mwaa-local-runner pull request #28
Opened 2021-06-28 22:10 UTC by DaniDasBoot

*Issue #27:*

*Description of changes:*

Added logic to entrypoint.sh to only generate the fernet key if it already hasn't been changed from `$FERNET_KEY` in airflow.cfg

```
#Add fernet key to airflow.cfg file:

if grep -q '$FERNET_KEY' /usr/local/airflow/airflow.cfg; then
    echo "fernet_key not set in airflow.cfg!"
    sed -i 's/$FERNET_KEY/TEMP_KEY/' /usr/local/airflow/airflow.cfg
    : "${AIRFLOW__CORE__FERNET_KEY:=${FERNET_KEY_GEN:=$(python -c "from cryptography.fernet import Fernet; FERNET_KEY = Fernet.generate_key().decode(); print(FERNET_KEY)")}}"
    sed -i "s/TEMP_KEY/$AIRFLOW__CORE__FERNET_KEY/" /usr/local/airflow/airflow.cfg
    echo "fernet_key is now set in airflow.cfg"
  else
    echo "fernet_key is already set in airflow.cfg"
fi

```

I commented out the lines that set the variable in the beginning of entrypoint.sh and then set it to an environment variable since airflow.cfg will store this info.

After testing, this lets you add a variable with `airflow variable -s "Key1" "Value1"` within the an exec session on the container. In addition, these airflow variables can then be seen in the airflow UI. Likewise, a variable can be set in the UI and a user can see it in the CLI since both the CLI and the UI are using the same fernet key.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-28 22:22 UTC, ashley-mallia commented
This is a good change, I’ll test if it fixes my issue.

2021-07-03 04:33 UTC, ashley-mallia approved these changes

2021-07-03 04:38 UTC, ashley-mallia requested changes
This is a good change.
Could you squash merge this into one single commit to clearly show the actual changeset.

Also you commented out one lines in entrypoint.sh, imho just delete them.

2021-07-13 15:51 UTC, marcoracer approved these changes

2022-04-11 17:49 UTC, closed without merging