bugfix: match build platform to platform argument in docker-compose
aws/aws-mwaa-local-runner pull request #314
Opened 2023-09-18 18:36 UTC by enmyj

*Issue #, if available:*

*Description of changes:*

The platform used for `docker build` should match the platform used in `docker/docker-compose-local.yml` [here](https://github.com/aws/aws-mwaa-local-runner/blob/v2.2.2/docker/docker-compose-local.yml#L18)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-19 08:46 UTC, elashrry requested changes
I think you don't need to add it to the `docker run` commands since it is a single platform image.

2023-09-19 15:46 UTC, enmyj commented
@elashrry - good point, just updated to remove the `--platform` flag from the docker run commands (also removed the `DOCKER_PLATFORM` var)

2023-09-19 16:17 UTC, elashrry approved these changes

2023-12-17 11:15 UTC, mayushko26 commented
@elashrry Could you describe the testing you performed for this change? And if possible, describe the implications of this change; what behaviour difference would we see after this change is merged? 

Also, this looks like it could be useful for all versions, so we should make sure to follow this up with similar pull requests for all other branches.

2023-12-17 11:36 UTC, mayushko26 commented
FYI - Looks like this will also fix #331

2023-12-21 10:16 UTC, Walliee commented
Just stumbled here after creating #342. I can confirm that the error I describe in the issue no longer occur once the platform is specified to be `linux/amd64`

2024-10-06 21:33 UTC, closed without merging